# The script below parses XML output files generated by Genome Detective and extracts
nucleotide and protein-coding mutations for Rift Valley fever virus (RVFV)
genomes (M segment).
# The script was applied iteratively to Genome Detective XML outputs from multiple
African countries and outbreak periods. For each sequence, it extracts:
- Sequence identifier
- Assigned lineage
- Nucleotide mutations and counts
- Protein-coding mutations from the M segment
- Counts of Gn and Gc mutations based on amino-acid position
- Segment and gene annotation

# Country, host, and sampling year were harmonized across datasets during
post-processing in R to generate the final continent-wide mutation summary used
in downstream analyses.

######## Python script #######
  
import xml.etree.ElementTree as ET
import pandas as pd
import re

# Load XML file
xml_path = "_result.xml"  # Update this if your file is in a different path
tree = ET.parse(xml_path)
root = tree.getroot()

records = []

for seq in root.findall(".//sequence"):
    sequence_id = seq.attrib.get("name", "Unknown")
    country = "Angola"  # Update if needed
    host = "Non-human"
    year = "Unknown"
    segment = "M"
    gene_name = "Unknown"  # Left as unknown unless explicitly extracted

    # Lineage
    lineage = ""
    for concl in seq.findall(".//conclusion[@type='simple']"):
        assigned = concl.find("assigned")
        if assigned is not None and "Lineage" in assigned.findtext("name", ""):
            lineage = assigned.findtext("name")

    # Nucleotide Mutations
    nt_mut_elem = seq.find(".//nt-mutations")
    if nt_mut_elem is not None and nt_mut_elem.text:
        nt_mutations = nt_mut_elem.text.replace("&gt;", ">")
        total_nt_mutations = len(nt_mutations.split(", "))
    else:
        nt_mutations = ""
        total_nt_mutations = 0

    # Protein Mutations: collect ALL and calculate based on position
    cds_aa_elem = seq.find(".//cds-aa-mutations")
    all_protein_mutations_cleaned = [] # List to store mutations without prefix
    total_gn = 0
    total_gc = 0

    if cds_aa_elem is not None and cds_aa_elem.text:
        raw_protein = cds_aa_elem.text.replace("&gt;", ">")
        mutations = raw_protein.split(", ")

        for mut in mutations:
            # Remove the "RVFV_sM_gp1:" prefix
            cleaned_mut = re.sub(r'RVFV_sM_gp1:', '', mut).strip()
            all_protein_mutations_cleaned.append(cleaned_mut)

            # Use regex to find the number in the cleaned mutation string for Gn/Gc calculation
            # This regex looks for a letter(s) followed by digits, optionally followed by more characters
            match = re.search(r'([A-Za-z]+)(\d+)(.*)', cleaned_mut)
            if match:
                position_str = match.group(2) # Extract the number part
                try:
                    position = int(position_str)
                    if position <= 650:
                        total_gn += 1
                    else:
                        total_gc += 1
                except ValueError:
                    # Handle cases where the extracted 'number' isn't a valid integer
                    pass
            elif re.search(r'^\d+$', cleaned_mut.strip()): # Handle cases like '123' if they occur
                 try:
                    position = int(cleaned_mut.strip())
                    if position <= 650:
                        total_gn += 1
                    else:
                        total_gc += 1
                 except ValueError:
                    pass

    total_protein_mutations = len(all_protein_mutations_cleaned)
    protein_mutations_output = ", ".join(all_protein_mutations_cleaned)

    records.append({
        "Country": country,
        "Sequence ID": sequence_id,
        "Host": host,
        "Segment": segment,
        "Gene Name": "glycoprotein",
        "Total Gn": total_gn,
        "Total Gc": total_gc,
        "Protein Mutations": protein_mutations_output, # Use the cleaned mutations here
        "Total Protein Mutations": total_protein_mutations,
        "Nucleotide Mutations": nt_mutations,
        "Total Nucleotide Mutations": total_nt_mutations,
        "Lineage": lineage,
        "Year of Sample Collection": year
    })

# Export to Excel
df = pd.DataFrame(records)
output_path = "Angola_H-GD_Mutation_Summary.xlsx"
df.to_excel(output_path, index=False)

print(f"✅ Genome mutation summary written to '{output_path}'")
